### ISSUE TITLE
Connexion par Facebook tente de créer un nouvel utilisateur

### ISSUE THREAD

**Issue by julie-ramadanoski** [julie-ramadanoski/univoiturage#15]
Le mesage Laravel  lors d'une connexion par facebook est
cannot duplicate foreign key contraint sur le champs e-mail

**Comment by TonnelierFlorian** [comment]
Salut Julie, je viens d'arriver chez moi et presque prêt à travailler.
Donc je créer une nouvelle branche à partir de la master c'est ça ? Je vais
essayer de régler le problème avec facebook et voir ce je peux faire
ensuite. Par exemple le mail lorsque l'on a oublier notre mot de passe, il
me semble l'avoir écrit mais pas mis en place.

2016-03-28 17:03 GMT+02:00 Ramadanoski Julie <notifications@github.com>:

**Comment by julie-ramadanoski** [comment]
Salut,

Donne moi ton numéro je t'appelle

Julie

Le 28 mars 2016 à 17:06, TonnelierFlorian <notifications@github.com> a
écrit :

**Comment by TonnelierFlorian** [comment]
06-11-36-44-17

Le 28 mars 2016 à 17:08, Ramadanoski Julie <notifications@github.com> a
écrit :

**Comment by TonnelierFlorian** [comment]
Voila ça retourne bien au bon endroit, mais il y a une nouvelle erreur pour le certificat.
avant c'était la 60 maintenant la 77. Je sais pas si ça a un rapport avec le serveur ou non.

RequestException in CurlFactory.php line 187:
cURL error 77: error setting certificate verify locations:
CAfile: /var/www/html/univoiturage
CApath: /etc/ssl/certs (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by julie-ramadanoski** [comment]
Vous aviez la solution, pourquoi vous avez pas mis le nom du fichier dans la variable de curl ?

![capture2](https://cloud.githubusercontent.com/assets/10398031/14089018/f5b7cffa-f532-11e5-833d-80a2bde029c0.PNG)

> service apache2 restart # et c'était fini.

Maintenant le ticket c'est cette magnifique erreur 

> Integrity constraint violation: 1062 Duplicate entry 'email@yopmail.com' for key 'users_email_unique'

**Comment by TonnelierFlorian** [comment]
Oui pas eu le temps on était parti chez mathias

2016-03-28 22:21 GMT+02:00 Ramadanoski Julie notifications@github.com:

**Comment by TonnelierFlorian** [comment]
Corrigé, j'ai remplacé l'id facebook par l'email puisqu'il est unique aussi
